"""Location table

Revision ID: c52b34ca8fa8
Revises: d792b80d8764
Create Date: 2017-10-16 13:42:42.746211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b34ca8fa8'
down_revision = 'd792b80d8764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('north', sa.Integer(), nullable=True),
    sa.Column('east', sa.Integer(), nullable=True),
    sa.Column('south', sa.Integer(), nullable=True),
    sa.Column('west', sa.Integer(), nullable=True),
    sa.Column('up', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('deathroom', sa.Boolean(), nullable=True),
    sa.Column('nobr', sa.Boolean(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
